### ISSUE TITLE
Closes out of unity

### ISSUE THREAD

**Issue by JohnCage1** [VRLabs/Avatars-3.0-Manager#24] opened 2023-09-30 06:21 UTC
The issue I am having is when setting up an FX, each time it just freezes my unity

**Comment by jellejurre** [comment] 2024-03-18 19:47
I'm going to guess this is a duplicate of #26 and you were accidentally merging a contorller onto itself. if not, feel free to open a new issue with steps to recreate it or ask for help in discord.vrlabs.dev

**Closed by jellejurre** 2024-03-18 19:47 UTC
